language: cpp
compiler:
    - clang
    - gcc
addons:
    apt:
        sources:
            - boost-latest
        packages:
            - libboost1.55-all-dev
install:
    - autoreconf --install --force
test:
    - make check
